name: 'Team BBailey'
markdown: redcarpet
highlighter: pygments
exclude: [
  'node_modules',
  'bower_components',
  'bower.json',
  'Gruntfile.js',
  'package.json',
  'Gemfile',
  'Gemfile.lock',
##  'css',
#  'sass',
##  'js',
#  'env',
#  'tmp'
  ]

destination: ./_site
show_disqus: false
